# Generated by Django 4.0.1 on 2022-01-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='option_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='statement',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
