# Generated by Django 3.1.7 on 2022-02-28 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220228_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='sni_number',
        ),
    ]
